language: java
env:
  global:
  - GIT_USERNAME=Travis CI
  - GIT_EMAIL=builds@travis-ci.com
  - TAG=$(./pipeline.sh getProperty version gradle.properties)
  - LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\n')
  - CD_COMMIT_MESSAGE='[travis] Automated update'
  - GITHUB_USER=dermotmburke
  - secure: Uixqu1VoPUGeWCSnZ2MnymTlO18QYWlRqIAomiDoDHsMiivxj9oGa2D+yoe1nh7t/NT0uPQUCJ/+UQCP8nu/0SO1jM5nioCNrjegy/rXZovsOrUOWoxs2f2O0QaQ2tPUqGaTV65TI9OtjzniV459CoPWUu9qKeD2SKnKXrRDNJ7CYe03JqPmSS7x6rmLbDI7ba8rszOvHqw/qCJO7i1svr2ew9Yd9xiALVgodgrfAd8kEc5i7hSnq5LXOI3Yg5NkXVD9knncDcj+T7iz3DSlubm7JRJXKVDxQPXx+JUXZgNUJ+7O61K8wLDFYCFhrmdlUXUMngO018xbnHGkicIldiK7LhTBZX5ASeEuRSgCFW6bUL1HRm1K4ssuBkxUzQmCsAwXqNyMD1eJUv1A3BDbUE9yKMuEWFD6ifFsJfzb31pYhWHxlKR6JRxWmfrh/kuAJjdlzcxaHtYcdGYE5q1/EZdRkuL0b343tyZTGP4OjnNsNuXllwP3swibUsOB6F48SvsufCwPRcid3yxdjdUC7uL8mX1EJ8xHw2GH/wYQklZgzBF1YlBl1L8CXNWH3n4IgAYVy2gTdORFzSVuKAJ9hEsENeYzzjc0EYp5b+oL+JnVh+IaVVolqWk19zm1A2WSfh1OFUGbTuR+xa0PsG26l+gPC6kqXPI8drBLubBvVNE=
  - secure: RuJBf2N2mP8k4iYLSH/1TGvhEphfqoKBKsQKgmrWEyP7Y59QM4H9c0MCVezXEz6AygN27JnmhleIXloeYe5rI0TPjCm8kqCTA6rMaJ1fvIL7fBwQjCivMVxgAsGcVJCfxgTYIIhIOnvPpbbqLLZWW+Si+1I3lmxGJtQDy5GwGo3qgxtyHdjsNPPnr0xB4udvLI9oPE/flaGEGCb8lntB6suCexHnpQvBNDJZ8ThvjVJA0xPNlC2F4b/+DX1Ym7SLfTgo8CUTxGhfF7aYF/g5N7J9IE/q5obzCU60u2Y6HuObW0F86SSz/AKjplWDNlq20lylzWqWZlsubbdEW2ybP8/seTn+rcGgN6RTUpaudPXNpxFb+RnLqQR4WkG3hA9hM5qcmXr21wL9Eqchqg6BMarkeolr8CDfTjyByUM7aiWo+Un6US5HObGGHauFG2OQXoHRbHt1Bf6IF+gTsvRBpaVF+5n6v3BdqAS4I4IKS8Kl71csOMrSgi2ajfsZOtMfPfUo6MLOQJRHix6JiUHyAfGQxh+RJzzDz4vmT03T/1IZj8BMF2yX8noRMNgJGjwssWzEWy8f5jyFGJoUoaAyhAPFkLds0KnSUoPAae639uLatdPeigGsnl2l47GeKTXBoeKH/76o6VSqYlpwlFf6lyneiPElpmXh7hllVkjiP2k=
script:
- travis_wait 30 ./pipeline.sh build
before_deploy:
- ./pipeline.sh tag
deploy:
  - provider: script
    script: gradle bintrayUpload -PbintrayUser=buildit -PbintrayKey=$BINTRAY_TOKEN -PdryRun=false
    skip_cleanup: true
    on:
      branch: master
      tags: false
      condition: '"${LAST_COMMIT_MESSAGE}" != "${CD_COMMIT_MESSAGE}"'
after_deploy:
- ./pipeline.sh bump
- ./pipeline.sh docs